// MOCK TEMPORAL — este archivo se borra cuando se conecta Firestore.
// productsService.js es el único archivo que lo importa; el resto de
// la app nunca debería importar esto directamente.
//
// Campos: id, name, image, category, brand, condition, year, hours,
// hoursValue, detail, power, traction, workWidth, featured.
// Los mismos nombres de campo deben usarse en los documentos de
// Firestore para que la migración no rompa nada.

export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: "John Deere 6155J",
    image: "/tractor-red.png",
    category: "Tractores",
    brand: "John Deere",
    condition: "usado",
    year: 2018,
    hours: "5.200 hs",
    hoursValue: 5200,
    detail: "Potencia: 155 HP",
    power: 155,
    traction: "Doble tracción (4x4)",
    workWidth: null,
    featured: true,
  },
  {
    id: 2,
    name: "Crucianelli Pionera 3520",
    image: "/sembradora-red.png",
    category: "Sembradoras",
    brand: "Case IH",
    condition: "nuevo",
    year: 2021,
    hours: "0 km",
    hoursValue: 0,
    detail: "21 líneas a 52,5 cm",
    power: null,
    traction: null,
    workWidth: 11,
    featured: true,
  },
  {
    id: 3,
    name: "New Holland CX740",
    image: "/cosechadora-yellow.png",
    category: "Cosechadoras",
    brand: "New Holland",
    condition: "usado",
    year: 2016,
    hours: "2.800 hs",
    hoursValue: 2800,
    detail: "Plataforma 35 pies",
    power: 421,
    traction: "Doble tracción (4x4)",
    workWidth: 10.6,
    featured: true,
  },
  {
    id: 4,
    name: "Rastra TBeH 28 Discos",
    image: "/rastra-red.png",
    category: "Rastrillos",
    brand: "Metalfor",
    condition: "usado",
    year: 2019,
    hours: "Muy buen estado",
    hoursValue: 1800,
    detail: "28 discos dentados",
    power: null,
    traction: null,
    workWidth: 6.2,
    featured: true,
  },
  {
    id: 5,
    name: "Rastrillo Rotativo",
    image: "/rastrillo-roto.png",
    category: "Rastrillos",
    brand: "Kuhn",
    condition: "usado",
    year: 2017,
    hours: "Buen estado",
    hoursValue: 2400,
    detail: "Ancho de trabajo 6,5 m",
    power: null,
    traction: null,
    workWidth: 6.5,
    featured: true,
  },
  {
    id: 6,
    name: "Case IH Puma 165",
    image: "/tractor-red.png",
    category: "Tractores",
    brand: "Case IH",
    condition: "nuevo",
    year: 2024,
    hours: "0 hs",
    hoursValue: 0,
    detail: "Potencia: 165 HP",
    power: 165,
    traction: "Doble tracción (4x4)",
    workWidth: null,
    featured: false,
  },
  {
    id: 7,
    name: "Claas Lexion 5700",
    image: "/cosechadora-yellow.png",
    category: "Cosechadoras",
    brand: "Claas",
    condition: "nuevo",
    year: 2023,
    hours: "120 hs",
    hoursValue: 120,
    detail: "Plataforma 40 pies",
    power: 476,
    traction: "Doble tracción (4x4)",
    workWidth: 12.2,
    featured: false,
  },
  {
    id: 8,
    name: "Jacto Uniport 3030",
    image: "/category-cosechadora.jpg",
    category: "Pulverizadoras",
    brand: "Jacto",
    condition: "usado",
    year: 2020,
    hours: "1.100 hs",
    hoursValue: 1100,
    detail: "Botalón de 30 m",
    power: 210,
    traction: "Simple (2x4)",
    workWidth: 30,
    featured: false,
  },
  {
    id: 9,
    name: "AGCO Valtra A950",
    image: "/tractor-red.png",
    category: "Tractores",
    brand: "AGCO",
    condition: "usado",
    year: 2015,
    hours: "6.400 hs",
    hoursValue: 6400,
    detail: "Potencia: 95 HP",
    power: 95,
    traction: "Simple (2x4)",
    workWidth: null,
    featured: false,
  },
  {
    id: 10,
    name: "Kuhn Espro 4000",
    image: "/sembradora-red.png",
    category: "Sembradoras",
    brand: "Kuhn",
    condition: "nuevo",
    year: 2022,
    hours: "0 km",
    hoursValue: 0,
    detail: "Sembradora neumática",
    power: null,
    traction: null,
    workWidth: 4,
    featured: false,
  },
];